base_url = "https://nakatechlabs.com"
title = "NakaTechLabs"
description = "Personal knowledge base for guides, notes, and tutorials."
compile_sass = true
build_search_index = true

taxonomies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[markdown]

[markdown.highlighting]
theme = "tokyo-night"

[extra]
author = "Aito Nakajima"
copyright = "NakaTechLabs"
main_nav = [
    { name = "Home", url = "/" },
    { name = "Blog", url = "/blog/" },
    { name = "Categories", url = "/categories/" },
]
social_links = [
    { name = "github", url = "https://www.github.com/gmskazi", icon = "github" },
]
